### PR TITLE
fitsio: fix float64 formatting #54

### PR DESCRIPTION
**Pull request by bjet007**
fix: Change printing of float64 from %f to %#20g.

### CODE REVIEW

**Review by sbinet — APPROVED** [review]
LGTM.

thanks a lot.

last thing before I can merge this PR: could you send another one against [astrogo/license](https://github.com/astrogo/license) adding yourself to the `AUTHORS` and/or `CONTRIBUTORS` files?

thanks again.

**Comment by bjet007** [comment]
While re-reading the spec, I realized that the exponent letter need to be uppercased. So I change the formatting to do that and I did add few other test.

I kept the commit separated for review, but I can squash them before the merge.

Ben

**Review by sbinet — APPROVED** [review]
still LGTM

(nice catch wrt the `E` vs `e` case)

**Comment by sbinet** [comment]
(I'll squash when I'll merge that PR in)

**Comment by sbinet** [comment]
needs https://github.com/astrogo/license/pull/5

**Comment by sbinet** [comment]
thanks again.

**Pull request merged**
